# Generated by Django 3.0.5 on 2020-04-15 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0002_notes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notes',
            unique_together={('user', 'name')},
        ),
    ]
